package com.probestack.forgestudio.design.service;

import com.probestack.forgestudio.design.model.Account;
import com.probestack.forgestudio.design.model.CreateAccountRequest;
import com.probestack.forgestudio.design.repository.CreateAccountRequestRepository;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Number;
import java.lang.NumberFormatException;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import org.springframework.beans.BeanUtils;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

/**
 * Service layer for CreateAccountRequest operations.
 *
 * <p>This service uses MongoDB repository for data persistence.</p>
 *
 * @author Generated by ProbeStack CodeGen
 * <p>Note: Mapper methods use BeanUtils.copyProperties() for automatic field mapping.</p>
 */
@Service
public class AccountsService {
    private final CreateAccountRequestRepository createAccountRequestRepository;

    public AccountsService(CreateAccountRequestRepository createAccountRequestRepository) {
        this.createAccountRequestRepository = createAccountRequestRepository;
    }

    public ResponseEntity<Account> createAccount(CreateAccountRequest createAccountRequest) {
        // Save the entity to database
        CreateAccountRequest savedCreateAccountRequest = createAccountRequestRepository.save(createAccountRequest);
        // Map entity to response DTO
        Account response = mapToAccount(savedCreateAccountRequest);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    public ResponseEntity<Account> getAccount(String accountId) {
        // Retrieve entity by ID from database
        Long repositoryId = toRepositoryId(accountId);
        Optional<CreateAccountRequest> entity = createAccountRequestRepository.findById(repositoryId);
        // Map entity to response DTO
        return entity.map(this::mapToAccount).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build());
    }

    public ResponseEntity<List<Account>> listAccounts() {
        // Retrieve all entities from database
        List<CreateAccountRequest> entities = createAccountRequestRepository.findAll();
        // Map entities to response DTOs
        List<Account> responses = entities.stream().map(this::mapToAccount).collect(Collectors.toList());
        return ResponseEntity.ok(responses);
    }

    /**
     * Converts OpenAPI path IDs to the repository ID type.
     */
    private Long toRepositoryId(Object id) {
        if (id == null) {
            return null;
        }
        if (id instanceof Long value) {
            return value;
        }
        if (id instanceof Integer value) {
            return value.longValue();
        }
        if (id instanceof Number value) {
            return value.longValue();
        }
        String text = id.toString();
        try {
            return Long.valueOf(text);
        } catch (NumberFormatException ignored) {
            return (long) text.hashCode();
        }
    }

    /**
     * Maps CreateAccountRequest entity to Account response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private Account mapToAccount(CreateAccountRequest entity) {
        // Create new response object
        Account response = new Account();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }
}
