package com.probestack.forgestudio.design.service;

import com.probestack.forgestudio.design.model.PaymentRequest;
import com.probestack.forgestudio.design.model.PaymentResponse;
import com.probestack.forgestudio.design.repository.PaymentRequestRepository;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Number;
import java.lang.NumberFormatException;
import java.lang.Object;
import java.lang.String;
import org.springframework.beans.BeanUtils;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

/**
 * Service layer for PaymentRequest operations.
 *
 * <p>This service uses MongoDB repository for data persistence.</p>
 *
 * @author Generated by ProbeStack CodeGen
 * <p>Note: Mapper methods use BeanUtils.copyProperties() for automatic field mapping.</p>
 */
@Service
public class PaymentsService {
    private final PaymentRequestRepository paymentRequestRepository;

    public PaymentsService(PaymentRequestRepository paymentRequestRepository) {
        this.paymentRequestRepository = paymentRequestRepository;
    }

    public ResponseEntity<PaymentResponse> createPayment(PaymentRequest paymentRequest) {
        // Save the entity to database
        PaymentRequest savedPaymentRequest = paymentRequestRepository.save(paymentRequest);
        // Map entity to response DTO
        PaymentResponse response = mapToPaymentResponse(savedPaymentRequest);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    /**
     * Converts OpenAPI path IDs to the repository ID type.
     */
    private Long toRepositoryId(Object id) {
        if (id == null) {
            return null;
        }
        if (id instanceof Long value) {
            return value;
        }
        if (id instanceof Integer value) {
            return value.longValue();
        }
        if (id instanceof Number value) {
            return value.longValue();
        }
        String text = id.toString();
        try {
            return Long.valueOf(text);
        } catch (NumberFormatException ignored) {
            return (long) text.hashCode();
        }
    }

    /**
     * Maps PaymentRequest entity to PaymentResponse response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private PaymentResponse mapToPaymentResponse(PaymentRequest entity) {
        // Create new response object
        PaymentResponse response = new PaymentResponse();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }
}
