package com.probestack.forgestudio.design.service;

import com.probestack.forgestudio.design.model.BalanceSheet;
import com.probestack.forgestudio.design.repository.BalanceSheetRepository;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Number;
import java.lang.NumberFormatException;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

/**
 * Service layer for BalanceSheet operations.
 *
 * <p>This service uses MongoDB repository for data persistence.</p>
 *
 * @author Generated by ProbeStack CodeGen
 */
@Service
public class ReportsService {
    private final BalanceSheetRepository balanceSheetRepository;

    public ReportsService(BalanceSheetRepository balanceSheetRepository) {
        this.balanceSheetRepository = balanceSheetRepository;
    }

    public ResponseEntity<BalanceSheet> getBalanceSheet(Integer fiscalYear) {
        // Retrieve all entities from database
        List<BalanceSheet> entities = balanceSheetRepository.findAll();
        return entities.isEmpty() ? ResponseEntity.notFound().build() : ResponseEntity.ok(entities.get(0));
    }

    /**
     * Converts OpenAPI path IDs to the repository ID type.
     */
    private Long toRepositoryId(Object id) {
        if (id == null) {
            return null;
        }
        if (id instanceof Long value) {
            return value;
        }
        if (id instanceof Integer value) {
            return value.longValue();
        }
        if (id instanceof Number value) {
            return value.longValue();
        }
        String text = id.toString();
        try {
            return Long.valueOf(text);
        } catch (NumberFormatException ignored) {
            return (long) text.hashCode();
        }
    }
}
