package com.probestack.forgestudio.design.service;

import com.probestack.forgestudio.design.model.CreateTransactionRequest;
import com.probestack.forgestudio.design.model.Transaction;
import com.probestack.forgestudio.design.repository.CreateTransactionRequestRepository;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Number;
import java.lang.NumberFormatException;
import java.lang.Object;
import java.lang.String;
import java.time.LocalDate;
import java.util.List;
import java.util.stream.Collectors;
import org.springframework.beans.BeanUtils;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

/**
 * Service layer for CreateTransactionRequest operations.
 *
 * <p>This service uses MongoDB repository for data persistence.</p>
 *
 * @author Generated by ProbeStack CodeGen
 * <p>Note: Mapper methods use BeanUtils.copyProperties() for automatic field mapping.</p>
 */
@Service
public class TransactionsService {
    private final CreateTransactionRequestRepository createTransactionRequestRepository;

    public TransactionsService(
            CreateTransactionRequestRepository createTransactionRequestRepository) {
        this.createTransactionRequestRepository = createTransactionRequestRepository;
    }

    public ResponseEntity<Transaction> createTransaction(
            CreateTransactionRequest createTransactionRequest) {
        // Save the entity to database
        CreateTransactionRequest savedCreateTransactionRequest = createTransactionRequestRepository.save(createTransactionRequest);
        // Map entity to response DTO
        Transaction response = mapToTransaction(savedCreateTransactionRequest);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    public ResponseEntity<List<Transaction>> listTransactions(String accountId, LocalDate startDate,
            LocalDate endDate) {
        // Retrieve all entities from database
        List<CreateTransactionRequest> entities = createTransactionRequestRepository.findAll();
        // Map entities to response DTOs
        List<Transaction> responses = entities.stream().map(this::mapToTransaction).collect(Collectors.toList());
        return ResponseEntity.ok(responses);
    }

    /**
     * Converts OpenAPI path IDs to the repository ID type.
     */
    private Long toRepositoryId(Object id) {
        if (id == null) {
            return null;
        }
        if (id instanceof Long value) {
            return value;
        }
        if (id instanceof Integer value) {
            return value.longValue();
        }
        if (id instanceof Number value) {
            return value.longValue();
        }
        String text = id.toString();
        try {
            return Long.valueOf(text);
        } catch (NumberFormatException ignored) {
            return (long) text.hashCode();
        }
    }

    /**
     * Maps CreateTransactionRequest entity to Transaction response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private Transaction mapToTransaction(CreateTransactionRequest entity) {
        // Create new response object
        Transaction response = new Transaction();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }
}
