/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.probestack.forgestudio.design.api;

import java.math.BigDecimal;
import com.probestack.forgestudio.design.model.CreateOrderRequest;
import com.probestack.forgestudio.design.model.Order;
import com.probestack.forgestudio.design.model.Product;
import com.probestack.forgestudio.design.model.UpdateOrderStatusRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-05-08T17:13:08.912352659Z[GMT]")@Validated
@Tag(name = "Default", description = "the Default API")
public interface DefaultApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /orders/{orderId} : Get order details
     *
     * @param orderId  (required)
     * @return Order details (status code 200)
     *         or Order not found (status code 404)
     */
    @Operation(
        operationId = "ordersOrderIdGet",
        summary = "Get order details",
        responses = {
            @ApiResponse(responseCode = "200", description = "Order details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Order.class))
            }),
            @ApiResponse(responseCode = "404", description = "Order not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/orders/{orderId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Order> ordersOrderIdGet(
        @Parameter(name = "orderId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("orderId") String orderId
    ) {
                        getRequest().ifPresent(request -> {
                    for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                        if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                            String exampleString = "{ \"totalAmount\" : 6.027456183070403, \"orderId\" : \"orderId\", \"customerId\" : \"customerId\", \"items\" : [ { \"quantity\" : 0, \"productId\" : \"productId\" }, { \"quantity\" : 0, \"productId\" : \"productId\" } ], \"status\" : \"CREATED\" }";
                            ApiUtil.setExampleResponse(request, "application/json", exampleString);
                            break;
                        }
                    }
                });
                return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                                            }


    /**
     * PUT /orders/{orderId}/status : Update order status
     *
     * @param orderId  (required)
     * @param updateOrderStatusRequest  (required)
     * @return Order status updated (status code 200)
     */
    @Operation(
        operationId = "ordersOrderIdStatusPut",
        summary = "Update order status",
        responses = {
            @ApiResponse(responseCode = "200", description = "Order status updated")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/orders/{orderId}/status",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> ordersOrderIdStatusPut(
        @Parameter(name = "orderId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("orderId") String orderId,
        @Parameter(name = "UpdateOrderStatusRequest", description = "", required = true) @Valid @RequestBody UpdateOrderStatusRequest updateOrderStatusRequest
    ) {
                        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                    }


    /**
     * POST /orders : Create order
     *
     * @param createOrderRequest  (required)
     * @return Order created (status code 201)
     */
    @Operation(
        operationId = "ordersPost",
        summary = "Create order",
        responses = {
            @ApiResponse(responseCode = "201", description = "Order created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Order.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/orders",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Order> ordersPost(
        @Parameter(name = "CreateOrderRequest", description = "", required = true) @Valid @RequestBody CreateOrderRequest createOrderRequest
    ) {
                        getRequest().ifPresent(request -> {
                    for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                        if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                            String exampleString = "{ \"totalAmount\" : 6.027456183070403, \"orderId\" : \"orderId\", \"customerId\" : \"customerId\", \"items\" : [ { \"quantity\" : 0, \"productId\" : \"productId\" }, { \"quantity\" : 0, \"productId\" : \"productId\" } ], \"status\" : \"CREATED\" }";
                            ApiUtil.setExampleResponse(request, "application/json", exampleString);
                            break;
                        }
                    }
                });
                return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                                            }


    /**
     * GET /products : Get all products
     *
     * @param category  (optional)
     * @param priceMin  (optional)
     * @param priceMax  (optional)
     * @return List of products (status code 200)
     */
    @Operation(
        operationId = "productsGet",
        summary = "Get all products",
        responses = {
            @ApiResponse(responseCode = "200", description = "List of products", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Product.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/products",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Product>> productsGet(
        @Parameter(name = "category", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "category", required = false) String category,
        @Parameter(name = "priceMin", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "priceMin", required = false) BigDecimal priceMin,
        @Parameter(name = "priceMax", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "priceMax", required = false) BigDecimal priceMax
    ) {
                        getRequest().ifPresent(request -> {
                    for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                        if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                            String exampleString = "[ { \"productId\" : \"productId\", \"price\" : 0.8008281904610115, \"name\" : \"name\", \"description\" : \"description\", \"stock\" : 6 }, { \"productId\" : \"productId\", \"price\" : 0.8008281904610115, \"name\" : \"name\", \"description\" : \"description\", \"stock\" : 6 } ]";
                            ApiUtil.setExampleResponse(request, "application/json", exampleString);
                            break;
                        }
                    }
                });
                return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                                            }


    /**
     * GET /products/{productId} : Get product by ID
     *
     * @param productId  (required)
     * @return Product details (status code 200)
     *         or Product not found (status code 404)
     */
    @Operation(
        operationId = "productsProductIdGet",
        summary = "Get product by ID",
        responses = {
            @ApiResponse(responseCode = "200", description = "Product details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Product.class))
            }),
            @ApiResponse(responseCode = "404", description = "Product not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/products/{productId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Product> productsProductIdGet(
        @Parameter(name = "productId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("productId") String productId
    ) {
                        getRequest().ifPresent(request -> {
                    for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                        if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                            String exampleString = "{ \"productId\" : \"productId\", \"price\" : 0.8008281904610115, \"name\" : \"name\", \"description\" : \"description\", \"stock\" : 6 }";
                            ApiUtil.setExampleResponse(request, "application/json", exampleString);
                            break;
                        }
                    }
                });
                return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                                            }

}
