/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.probestack.forgestudio.design.api;

import com.probestack.forgestudio.design.model.Appointment;
import com.probestack.forgestudio.design.model.Patient;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-05-13T04:05:50.787357823Z[GMT]")@Validated
@Tag(name = "Default", description = "the Default API")
public interface DefaultApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /appointments : Create appointment
     *
     * @param appointment  (required)
     * @return Appointment created (status code 201)
     */
    @Operation(
        operationId = "appointmentsPost",
        summary = "Create appointment",
        responses = {
            @ApiResponse(responseCode = "201", description = "Appointment created")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/appointments",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> appointmentsPost(
        @Parameter(name = "Appointment", description = "", required = true) @Valid @RequestBody Appointment appointment
    ) {
                        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                    }


    /**
     * GET /patients/{patientId} : Get patient details
     *
     * @param patientId  (required)
     * @return Patient details (status code 200)
     */
    @Operation(
        operationId = "patientsPatientIdGet",
        summary = "Get patient details",
        responses = {
            @ApiResponse(responseCode = "200", description = "Patient details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Patient.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/patients/{patientId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Patient> patientsPatientIdGet(
        @Parameter(name = "patientId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("patientId") String patientId
    ) {
                        getRequest().ifPresent(request -> {
                    for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                        if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                            String exampleString = "{ \"gender\" : \"gender\", \"patientId\" : \"patientId\", \"name\" : \"name\", \"age\" : 0 }";
                            ApiUtil.setExampleResponse(request, "application/json", exampleString);
                            break;
                        }
                    }
                });
                return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                                            }


    /**
     * POST /patients : Create patient
     *
     * @param patient  (required)
     * @return Patient created (status code 201)
     */
    @Operation(
        operationId = "patientsPost",
        summary = "Create patient",
        responses = {
            @ApiResponse(responseCode = "201", description = "Patient created")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/patients",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> patientsPost(
        @Parameter(name = "Patient", description = "", required = true) @Valid @RequestBody Patient patient
    ) {
                        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                    }

}
